
class Subreddit {

  final bool default_set;
  final bool user_is_contributor;
  final String banner_img;
  final bool restrict_posting;
  final bool user_is_banned;
  final bool free_form_reports;
  final String community_icon;
  final bool show_media;
  final String icon_color;
  final bool user_is_muted;
  final String display_name;
  final Object header_img;
  final String title;
  final int coins;
  final bool over_18;
  final List<int> icon_size;
  final String primary_color;
  final String icon_img;
  final String description;
  final String submit_link_label;
  final Object header_size;
  final bool restrict_commenting;
  final int subscribers;
  final String submit_text_label;
  final bool is_default_icon;
  final String link_flair_position;
  final String display_name_prefixed;
  final String key_color;
  final String name;
  final bool is_default_banner;
  final String url;
  final Object banner_size;
  final bool user_is_moderator;
  final String public_description;
  final bool link_flair_enabled;
  final bool disable_contributor_requests;
  final String subreddit_type;
  final bool user_is_subscriber;

	Subreddit.fromJsonMap(Map<String, dynamic> map): 
		default_set = map["default_set"],
		user_is_contributor = map["user_is_contributor"],
		banner_img = map["banner_img"],
		restrict_posting = map["restrict_posting"],
		user_is_banned = map["user_is_banned"],
		free_form_reports = map["free_form_reports"],
		community_icon = map["community_icon"],
		show_media = map["show_media"],
		icon_color = map["icon_color"],
		user_is_muted = map["user_is_muted"],
		display_name = map["display_name"],
		header_img = map["header_img"],
		title = map["title"],
		coins = map["coins"],
		over_18 = map["over_18"],
		icon_size = List<int>.from(map["icon_size"]),
		primary_color = map["primary_color"],
		icon_img = map["icon_img"],
		description = map["description"],
		submit_link_label = map["submit_link_label"],
		header_size = map["header_size"],
		restrict_commenting = map["restrict_commenting"],
		subscribers = map["subscribers"],
		submit_text_label = map["submit_text_label"],
		is_default_icon = map["is_default_icon"],
		link_flair_position = map["link_flair_position"],
		display_name_prefixed = map["display_name_prefixed"],
		key_color = map["key_color"],
		name = map["name"],
		is_default_banner = map["is_default_banner"],
		url = map["url"],
		banner_size = map["banner_size"],
		user_is_moderator = map["user_is_moderator"],
		public_description = map["public_description"],
		link_flair_enabled = map["link_flair_enabled"],
		disable_contributor_requests = map["disable_contributor_requests"],
		subreddit_type = map["subreddit_type"],
		user_is_subscriber = map["user_is_subscriber"];

	Map<String, dynamic> toJson() {
		final Map<String, dynamic> data = new Map<String, dynamic>();
		data['default_set'] = default_set;
		data['user_is_contributor'] = user_is_contributor;
		data['banner_img'] = banner_img;
		data['restrict_posting'] = restrict_posting;
		data['user_is_banned'] = user_is_banned;
		data['free_form_reports'] = free_form_reports;
		data['community_icon'] = community_icon;
		data['show_media'] = show_media;
		data['icon_color'] = icon_color;
		data['user_is_muted'] = user_is_muted;
		data['display_name'] = display_name;
		data['header_img'] = header_img;
		data['title'] = title;
		data['coins'] = coins;
		data['over_18'] = over_18;
		data['icon_size'] = icon_size;
		data['primary_color'] = primary_color;
		data['icon_img'] = icon_img;
		data['description'] = description;
		data['submit_link_label'] = submit_link_label;
		data['header_size'] = header_size;
		data['restrict_commenting'] = restrict_commenting;
		data['subscribers'] = subscribers;
		data['submit_text_label'] = submit_text_label;
		data['is_default_icon'] = is_default_icon;
		data['link_flair_position'] = link_flair_position;
		data['display_name_prefixed'] = display_name_prefixed;
		data['key_color'] = key_color;
		data['name'] = name;
		data['is_default_banner'] = is_default_banner;
		data['url'] = url;
		data['banner_size'] = banner_size;
		data['user_is_moderator'] = user_is_moderator;
		data['public_description'] = public_description;
		data['link_flair_enabled'] = link_flair_enabled;
		data['disable_contributor_requests'] = disable_contributor_requests;
		data['subreddit_type'] = subreddit_type;
		data['user_is_subscriber'] = user_is_subscriber;
		return data;
	}
}
