import 'package:flutter_provider_app/models/user_profile/features.dart';
import 'package:flutter_provider_app/models/user_profile/subreddit.dart';

class UserInformation {
  final bool is_employee;
  final bool seen_layout_switch;
  final bool has_visited_new_profile;
  final bool pref_no_profanity;
  final bool has_external_account;
  final String pref_geopopular;
  final bool seen_redesign_modal;
  final bool pref_show_trending;
  final Subreddit subreddit;
  final bool is_sponsor;
  final Object gold_expiration;
  final bool has_gold_subscription;
  final int num_friends;
  final Features features;
  final bool has_android_subscription;
  final bool verified;
  final bool new_modmail_exists;
  final bool pref_autoplay;
  final int coins;
  final bool has_paypal_subscription;
  final bool has_subscribed_to_premium;
  final String id;
  final bool has_stripe_subscription;
  final bool seen_premium_adblock_modal;
  final bool can_create_subreddit;
  final bool over_18;
  final bool is_gold;
  final bool is_mod;
  final Object suspension_expiration_utc;
  final bool has_verified_email;
  final bool is_suspended;
  final bool pref_video_autoplay;
  final bool in_chat;
  final bool in_redesign_beta;
  final String icon_img;
  final bool has_mod_mail;
  final bool pref_nightmode;
  final String oauth_client_id;
  final bool hide_from_robots;
  final int link_karma;
  final bool force_password_reset;
  final int inbox_count;
  final bool pref_top_karma_subreddits;
  final bool has_mail;
  final bool pref_show_snoovatar;
  final String name;
  final int pref_clickgadget;
  final double created;
  final int gold_creddits;
  final double created_utc;
  final bool has_ios_subscription;
  final bool pref_show_twitter;
  final bool in_beta;
  final int comment_karma;
  final bool has_subscribed;
  final bool seen_subreddit_chat_ftux;

  UserInformation.fromJsonMap(Map<String, dynamic> map)
      : is_employee = map["is_employee"],
        seen_layout_switch = map["seen_layout_switch"],
        has_visited_new_profile = map["has_visited_new_profile"],
        pref_no_profanity = map["pref_no_profanity"],
        has_external_account = map["has_external_account"],
        pref_geopopular = map["pref_geopopular"],
        seen_redesign_modal = map["seen_redesign_modal"],
        pref_show_trending = map["pref_show_trending"],
        subreddit = Subreddit.fromJsonMap(map["subreddit"]),
        is_sponsor = map["is_sponsor"],
        gold_expiration = map["gold_expiration"],
        has_gold_subscription = map["has_gold_subscription"],
        num_friends = map["num_friends"],
        features = Features.fromJsonMap(map["features"]),
        has_android_subscription = map["has_android_subscription"],
        verified = map["verified"],
        new_modmail_exists = map["new_modmail_exists"],
        pref_autoplay = map["pref_autoplay"],
        coins = map["coins"],
        has_paypal_subscription = map["has_paypal_subscription"],
        has_subscribed_to_premium = map["has_subscribed_to_premium"],
        id = map["id"],
        has_stripe_subscription = map["has_stripe_subscription"],
        seen_premium_adblock_modal = map["seen_premium_adblock_modal"],
        can_create_subreddit = map["can_create_subreddit"],
        over_18 = map["over_18"],
        is_gold = map["is_gold"],
        is_mod = map["is_mod"],
        suspension_expiration_utc = map["suspension_expiration_utc"],
        has_verified_email = map["has_verified_email"],
        is_suspended = map["is_suspended"],
        pref_video_autoplay = map["pref_video_autoplay"],
        in_chat = map["in_chat"],
        in_redesign_beta = map["in_redesign_beta"],
        icon_img = map["icon_img"],
        has_mod_mail = map["has_mod_mail"],
        pref_nightmode = map["pref_nightmode"],
        oauth_client_id = map["oauth_client_id"],
        hide_from_robots = map["hide_from_robots"],
        link_karma = map["link_karma"],
        force_password_reset = map["force_password_reset"],
        inbox_count = map["inbox_count"],
        pref_top_karma_subreddits = map["pref_top_karma_subreddits"],
        has_mail = map["has_mail"],
        pref_show_snoovatar = map["pref_show_snoovatar"],
        name = map["name"],
        pref_clickgadget = map["pref_clickgadget"],
        created = map["created"],
        gold_creddits = map["gold_creddits"],
        created_utc = map["created_utc"],
        has_ios_subscription = map["has_ios_subscription"],
        pref_show_twitter = map["pref_show_twitter"],
        in_beta = map["in_beta"],
        comment_karma = map["comment_karma"],
        has_subscribed = map["has_subscribed"],
        seen_subreddit_chat_ftux = map["seen_subreddit_chat_ftux"];

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['is_employee'] = is_employee;
    data['seen_layout_switch'] = seen_layout_switch;
    data['has_visited_new_profile'] = has_visited_new_profile;
    data['pref_no_profanity'] = pref_no_profanity;
    data['has_external_account'] = has_external_account;
    data['pref_geopopular'] = pref_geopopular;
    data['seen_redesign_modal'] = seen_redesign_modal;
    data['pref_show_trending'] = pref_show_trending;
    data['subreddit'] = subreddit == null ? null : subreddit.toJson();
    data['is_sponsor'] = is_sponsor;
    data['gold_expiration'] = gold_expiration;
    data['has_gold_subscription'] = has_gold_subscription;
    data['num_friends'] = num_friends;
    data['features'] = features == null ? null : features.toJson();
    data['has_android_subscription'] = has_android_subscription;
    data['verified'] = verified;
    data['new_modmail_exists'] = new_modmail_exists;
    data['pref_autoplay'] = pref_autoplay;
    data['coins'] = coins;
    data['has_paypal_subscription'] = has_paypal_subscription;
    data['has_subscribed_to_premium'] = has_subscribed_to_premium;
    data['id'] = id;
    data['has_stripe_subscription'] = has_stripe_subscription;
    data['seen_premium_adblock_modal'] = seen_premium_adblock_modal;
    data['can_create_subreddit'] = can_create_subreddit;
    data['over_18'] = over_18;
    data['is_gold'] = is_gold;
    data['is_mod'] = is_mod;
    data['suspension_expiration_utc'] = suspension_expiration_utc;
    data['has_verified_email'] = has_verified_email;
    data['is_suspended'] = is_suspended;
    data['pref_video_autoplay'] = pref_video_autoplay;
    data['in_chat'] = in_chat;
    data['in_redesign_beta'] = in_redesign_beta;
    data['icon_img'] = icon_img;
    data['has_mod_mail'] = has_mod_mail;
    data['pref_nightmode'] = pref_nightmode;
    data['oauth_client_id'] = oauth_client_id;
    data['hide_from_robots'] = hide_from_robots;
    data['link_karma'] = link_karma;
    data['force_password_reset'] = force_password_reset;
    data['inbox_count'] = inbox_count;
    data['pref_top_karma_subreddits'] = pref_top_karma_subreddits;
    data['has_mail'] = has_mail;
    data['pref_show_snoovatar'] = pref_show_snoovatar;
    data['name'] = name;
    data['pref_clickgadget'] = pref_clickgadget;
    data['created'] = created;
    data['gold_creddits'] = gold_creddits;
    data['created_utc'] = created_utc;
    data['has_ios_subscription'] = has_ios_subscription;
    data['pref_show_twitter'] = pref_show_twitter;
    data['in_beta'] = in_beta;
    data['comment_karma'] = comment_karma;
    data['has_subscribed'] = has_subscribed;
    data['seen_subreddit_chat_ftux'] = seen_subreddit_chat_ftux;
    return data;
  }
}
